# Generated by Django 5.0.6 on 2024-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_source', models.CharField(max_length=50)),
                ('stock_cost', models.IntegerField(default=10)),
                ('stock_price', models.IntegerField(default=0)),
                ('stock_tonnage', models.CharField(max_length=50)),
            ],
        ),
    ]
