# Generated by Django 5.0.6 on 2024-08-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0003_rename_stock_price_stockx_issued_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockx',
            name='stock_ID',
        ),
    ]
