# Generated by Django 5.0.6 on 2024-08-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0004_remove_stockx_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='items',
            new_name='item',
        ),
    ]
