# Generated by Django 5.0.6 on 2024-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0005_rename_items_sales_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockx',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
