# Generated by Django 5.0.6 on 2024-09-02 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0006_alter_stockx_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deffered_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True)),
                ('item_bought_on_credit', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=datetime.datetime(2024, 9, 2, 20, 52, 10, 188300))),
                ('date_of_payment', models.DateField(default=datetime.datetime(2024, 9, 2, 20, 52, 10, 188300))),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 20, 52, 10, 186253)),
        ),
        migrations.AddField(
            model_name='sales',
            name='sells_agent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
