# Generated by Django 5.0.6 on 2024-09-03 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0007_deffered_payments_sales_branch_sales_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sells_agent',
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 14, 12, 17, 290971)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 14, 12, 17, 290971)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount_received',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 14, 12, 17, 290971)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit_price',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
