# Generated by Django 5.0.6 on 2024-09-07 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0009_sales_branch_name_sales_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 17, 53, 21, 774871)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 17, 53, 21, 774871)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 17, 53, 21, 774361)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
