# Generated by Django 5.0.6 on 2024-09-07 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0014_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 18, 8, 27, 381995)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 18, 8, 27, 381995)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 18, 8, 27, 381995)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
