# Generated by Django 5.0.6 on 2024-09-09 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalbook', '0018_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deffered_payments',
            name='quantity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='deffered_payments',
            name='unit_price',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 7, 40, 10, 600597)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 7, 40, 10, 600597)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 9, 7, 40, 10, 600597)),
        ),
    ]
